server:
  port: 10001
spring:
  application:
    name: bitcoin-pay

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: rm-wz9p7ne0m7sqb751fao.mysql.rds.aliyuncs.com
    username: tues
    password: tues1020